export interface OccupationDefinition {
  key: string;
  pointFormula: string; // e.g. "EDU*4", "EDU*2+DEX*2"
  skills: string[]; // keys of skills
  creditRating: [number, number]; // min, max
  skillRatios?: Record<string, number>; // optional skill allocation ratios (0-100)
}

export const OCCUPATIONS: OccupationDefinition[] = [
  {
    key: "antiquarian",
    pointFormula: "EDU*4",
    skills: [
      "appraise",
      "art_craft",
      "history",
      "library_use",
      "language_other",
      "spot_hidden",
      "charm",
      "navigate",
    ],
    creditRating: [30, 70],
    skillRatios: {
      appraise: 20,
      art_craft: 10,
      history: 20,
      library_use: 15,
      language_other: 10,
      spot_hidden: 10,
      charm: 5,
      navigate: 10,
    },
  },
  {
    key: "artist",
    pointFormula: "EDU*2+POW*2", // Simplified
    skills: [
      "art_craft",
      "history",
      "natural_world",
      "psychology",
      "language_other",
      "spot_hidden",
      "charm",
      "listen",
    ],
    creditRating: [9, 50],
    skillRatios: {
      art_craft: 25,
      history: 10,
      natural_world: 15,
      psychology: 10,
      language_other: 10,
      spot_hidden: 10,
      charm: 10,
      listen: 10,
    },
  },
  {
    key: "author",
    pointFormula: "EDU*4",
    skills: [
      "art_craft",
      "history",
      "library_use",
      "natural_world",
      "occult",
      "language_other",
      "psychology",
      "persuade",
    ],
    creditRating: [9, 30],
    skillRatios: {
      art_craft: 5,
      history: 15,
      library_use: 20,
      natural_world: 10,
      occult: 10,
      language_other: 15,
      psychology: 15,
      persuade: 10,
    },
  },
  {
    key: "doctor_of_medicine",
    pointFormula: "EDU*4",
    skills: [
      "first_aid",
      "language_other",
      "medicine",
      "psychology",
      "science",
      "charm",
      "library_use",
    ],
    creditRating: [30, 80],
    skillRatios: {
      first_aid: 15,
      language_other: 10,
      medicine: 30,
      psychology: 10,
      science: 20,
      charm: 5,
      library_use: 10,
    },
  },
  {
    key: "journalist",
    pointFormula: "EDU*4",
    skills: [
      "art_craft",
      "history",
      "library_use",
      "language_own",
      "psychology",
      "charm",
      "fast_talk",
      "spot_hidden",
    ],
    creditRating: [9, 30],
    skillRatios: {
      art_craft: 5,
      history: 15,
      library_use: 15,
      language_own: 15,
      psychology: 15,
      charm: 10,
      fast_talk: 15,
      spot_hidden: 10,
    },
  },
  {
    key: "police_detective",
    pointFormula: "EDU*2+DEX*2", // Simplified
    skills: [
      "art_craft",
      "disguise",
      "firearms_handgun",
      "law",
      "listen",
      "psychology",
      "spot_hidden",
      "charm",
    ],
    creditRating: [20, 50],
    skillRatios: {
      art_craft: 5,
      disguise: 10,
      firearms_handgun: 10,
      law: 15,
      listen: 15,
      psychology: 20,
      spot_hidden: 15,
      charm: 10,
    },
  },
  {
    key: "private_investigator",
    pointFormula: "EDU*2+DEX*2", // Simplified
    skills: [
      "art_craft",
      "disguise",
      "law",
      "library_use",
      "listen",
      "psychology",
      "spot_hidden",
      "charm",
    ],
    creditRating: [9, 30],
    skillRatios: {
      art_craft: 5,
      disguise: 15,
      law: 10,
      library_use: 15,
      listen: 15,
      psychology: 20,
      spot_hidden: 15,
      charm: 5,
    },
  },
  {
    key: "professor",
    pointFormula: "EDU*4",
    skills: [
      "library_use",
      "language_other",
      "language_own",
      "psychology",
      "science",
      "charm",
      "history",
    ],
    creditRating: [20, 70],
    skillRatios: {
      library_use: 15,
      language_other: 15,
      language_own: 10,
      psychology: 10,
      science: 25,
      charm: 5,
      history: 20,
    },
  },
  {
    key: "smuggler",
    pointFormula: "EDU*2+DEX*2",
    skills: [
      "appraise",
      "disguise",
      "fast_talk",
      "law",
      "locksmith",
      "psychology",
      "spot_hidden",
      "stealth",
    ],
    creditRating: [5, 50],
    skillRatios: {
      appraise: 10,
      disguise: 10,
      fast_talk: 15,
      law: 5,
      locksmith: 10,
      psychology: 10,
      spot_hidden: 20,
      stealth: 20,
    },
  },
  {
    key: "martial_arts_instructor",
    pointFormula: "EDU*2+DEX*2",
    skills: [
      "dodge",
      "fighting_brawl",
      "jump",
      "spot_hidden",
      "intimidate",
      "psychology",
      "first_aid",
      "language_other",
    ],
    creditRating: [9, 50],
    skillRatios: {
      dodge: 20,
      fighting_brawl: 25,
      jump: 10,
      spot_hidden: 10,
      intimidate: 10,
      psychology: 5,
      first_aid: 10,
      language_other: 10,
    },
  },
];
