export interface SkillDefinition {
  key: string;
  base: number;
}

export const SKILL_CATALOGUE: SkillDefinition[] = [
  { key: "accounting", base: 5 },
  { key: "acting", base: 5 },
  { key: "animal_handling", base: 5 },
  { key: "anthropology", base: 1 },
  { key: "appraise", base: 5 },
  { key: "archaeology", base: 1 },
  { key: "art_craft", base: 5 },
  { key: "artillery", base: 1 },
  { key: "charm", base: 15 },
  { key: "climb", base: 20 },
  { key: "computer_use", base: 5 },
  { key: "credit_rating", base: 0 },
  { key: "cthulhu_mythos", base: 0 },
  { key: "demolitions", base: 1 },
  { key: "disguise", base: 5 },
  { key: "diving", base: 1 },
  { key: "dodge", base: 0 }, // base is half DEX
  { key: "drive_auto", base: 20 },
  { key: "elec_repair", base: 10 },
  { key: "electronics", base: 1 },
  { key: "fast_talk", base: 5 },
  { key: "fighting_brawl", base: 25 },
  { key: "fighting_sword", base: 20 },
  { key: "firearms_bow", base: 15 },
  { key: "firearms_handgun", base: 20 },
  { key: "firearms_heavy", base: 10 },
  { key: "firearms_flamethrower", base: 10 },
  { key: "firearms_machine_gun", base: 10 },
  { key: "firearms_rifle_shotgun", base: 25 },
  { key: "firearms_submachine_gun", base: 15 },
  { key: "first_aid", base: 30 },
  { key: "history", base: 5 },
  { key: "hypnosis", base: 1 },
  { key: "intimidate", base: 15 },
  { key: "jump", base: 20 },
  { key: "language_other", base: 1 },
  { key: "language_own", base: 0 }, // base is EDU
  { key: "law", base: 5 },
  { key: "library_use", base: 20 },
  { key: "listen", base: 20 },
  { key: "locksmith", base: 1 },
  { key: "mech_repair", base: 10 },
  { key: "medicine", base: 1 },
  { key: "natural_world", base: 10 },
  { key: "navigate", base: 10 },
  { key: "occult", base: 5 },
  { key: "operate_heavy_machinery", base: 1 },
  { key: "persuade", base: 10 },
  { key: "pilot", base: 1 },
  { key: "psychoanalysis", base: 1 },
  { key: "psychology", base: 10 },
  { key: "read_lips", base: 1 },
  { key: "ride", base: 5 },
  { key: "science", base: 1 },
  { key: "sleight_of_hand", base: 10 },
  { key: "spot_hidden", base: 25 },
  { key: "stealth", base: 20 },
  { key: "survival", base: 10 },
  { key: "swim", base: 20 },
  { key: "throw", base: 20 },
  { key: "track", base: 10 },
];
